site_name: Dokumentasi WikiKamus base Sasak
repo_url: https://github.com/nikolaskhf/WikiKamus-Base-Sasak
site_description: Dokumentasi dasar untuk penyuntingan WikiKamus base Sasak
site_author: NikolasKHF
copyright: Konten pada situs ini dilisensikan di bawah <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.id">Lisensi CC BY-SA 4.0 International</a>.


nav:
  - Home: index.md
  - Menyunting: nyunting.md
  - Sumber daya: sumber_daya.md
  - Dasar-dasar:
    - Membuat akun: dasar/akun.md
    - Sintaks Wiki: dasar/sintaks.md

theme:
  name: readthedocs
  locale: id
  color_mode: dark
  user_color_mode_toggle: true

markdown_extensions:
  - toc:
      permalink: "#"
      separator: "_"
